In [1]:
import os
import pandas as pd

# 1. УЗНАТЬ ТЕКУЩИЙ ПУТЬ
current_dir = os.getcwd() 
print(f"Сейчас блокнот работает здесь: {current_dir}")

# 2. ЧТО ТАКОЕ r'' (Raw String)
# Буква 'r' перед кавычками отключает спецсимволы (например, \n или \t).
# Без неё Python выдаст ошибку SyntaxError на путях Windows.

# 3. ИМПОРТ ИЗ ЗАГРУЗОК (Пример)
# Используем r'' для корректной обработки обратных слэшей \
path = r'C:\Users\xenia\Downloads\archive (1)\2019.csv'

# Загрузка данных (замените 'data.csv' на ваше имя файла)
df = pd.read_csv(path) 

print(f"Путь для импорта сформирован: {path}")

Сейчас блокнот работает здесь: C:\Users\xenia
Путь для импорта сформирован: C:\Users\xenia\Downloads\archive (1)\2019.csv

In [2]:
# ТЕОРИЯ: Поиск строки по значению (Фильтрация)

# 1. Основной синтаксис: df[условие]
# Внутри скобок пишем: Название_Таблицы['Название_Колонки'] == 'Искомое_Значение'
# row = df[df['ID'] == 'A123']

# 2. Вывод без индекса (только данные):
# .values превращает строку таблицы в чистый массив данных
# print(row.values)

# 3. Поиск по всей таблице (если колонка неизвестна):
# .isin(['значение']) ищет везде, .any(axis=1) находит нужную строку
# full_search = df[df.isin(['уникальное_слово']).any(axis=1)]

# ИТОГ: Чтобы увидеть всю строку, достаточно:
# df[df['колонки'] == 'значение']

display(df)
row = df[df['Country or region'] == 'Russia']
row

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298
...,...,...,...,...,...,...,...,...,...
151,152,Rwanda,3.334,0.359,0.711,0.614,0.555,0.217,0.411
152,153,Tanzania,3.231,0.476,0.885,0.499,0.417,0.276,0.147
153,154,Afghanistan,3.203,0.350,0.517,0.361,0.000,0.158,0.025
154,155,Central African Republic,3.083,0.026,0.000,0.105,0.225,0.235,0.035
155,156,South Sudan,2.853,0.306,0.575,0.295,0.010,0.202,0.091

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
67,68,Russia,5.648,1.183,1.452,0.726,0.334,0.082,0.031

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Overall rank                  156 non-null    int64
 1   Country or region             156 non-null    object
 2   Score                         156 non-null    float64
 3   GDP per capita                156 non-null    float64
 4   Social support                156 non-null    float64
 5   Healthy life expectancy       156 non-null    float64
 6   Freedom to make life choices  156 non-null    float64
 7   Generosity                    156 non-null    float64
 8   Perceptions of corruption     156 non-null    float64
dtypes: float64(7), int64(1), object(1)
memory usage: 11.1+ KB

In [4]:
res_split=[] # создаем пустой список, куда сложим результат работы цикла
for i in range(len(df)): # запустим цикл длиной в размер матрицы (156 строк)
    x=df['Country or region'][i] # поочередно запишем в переменную название страны с помощью перебора
    res_split.append(x.lower()) # приведем название в нижний регистр (уже строку) и добавим в список

print(len(res_split)) # выведем длину списка
print(df.shape) # выведем размер матрицы 

df['Country or region_lower']=res_split # создадим новый столбец, добавив в него данные списка

display(df.head(4))

156
(156, 9)

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Country or region_lower
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393,finland
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410,denmark
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341,norway
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118,iceland

In [5]:
df['Country or region_lower_2']=df['Country or region'].apply(lambda x:x.lower())
display(df.head(4))

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Country or region_lower,Country or region_lower_2
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393,finland,finland
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410,denmark,denmark
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341,norway,norway
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118,iceland,iceland

In [6]:
# Преобразуйте столбец Score в целочисленный формат (тип данных — int), после чего вычислите среднее значение этого столбца. 
# Запишите полученный результат с точностью до двух знаков после запятой.

df['Score'] = df['Score'].astype(int)
df['Score'].mean()

4.948717948717949

In [7]:
# Вычислите среднее значение для каждой страны по столбцам Social support, Healthy life expectancy и Freedom to make life choices. 
# Затем запишите эти данные в новый столбец. В поле ответа внесите максимальное значение из полученного столбца, 
# округленное до двух знаков после запятой.
df['summary']=(df['Social support']+df['Healthy life expectancy']+df['Freedom to make life choices'])/3
display(round(max(df['summary']),2))

1.08

In [9]:
# Давайте вернёмся к оригинальному датасету за 2019 г. В этом задании работайте с оригинальными данными, без преобразований, 
# выполненных в задачах 1 и 2.

# Создайте новый столбец:
# Если название страны состоит из одного слова, то в новом столбце должно быть записано '1 слово в названии'.
# Если название страны состоит из двух и более слов, то в новом столбце должно быть записано '2 и более слов в названии'.

# Затем сгруппируйте данные по новому столбцу и вычислите среднее значение Score. 
# Ответ округлите до 2 знаков после запятой. В ответе укажите значение для стран с 2 и более словами в названии.
df = pd.read_csv(path) 

df['country_split']=df['Country or region'].apply(lambda x: x.split(' '))
df['len_country']=''
for i in range(len(df)):
    if len(df['country_split'][i])==1:
        df['len_country'][i]='1 слово в названии'
    if len(df['country_split'][i])>1:
        df['len_country'][i]='2 и более слов в названии'
df_gr=df.groupby('len_country')['Score'].agg('mean')
df_gr=df_gr.round(2)
display(df_gr.head(10))

C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='2 и более слов в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='2 и более слов в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='2 и более слов в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='2 и более слов в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='2 и более слов в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='2 и более слов в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='2 и более слов в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='2 и более слов в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='2 и более слов в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='2 и более слов в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len_country'][i]='1 слово в названии'
C:\Users\xenia\AppData\Local\Temp\ipykernel_12224\3618577372.py:16: SettingWithCopyWarning:

len_country
1 слово в названии           5.39
2 и более слов в названии    5.48
Name: Score, dtype: float64